### ISSUE TITLE
Some Countries and Languages do not select

### ISSUE THREAD

**Issue by lucasblackhurst** [replaysMike/react-country-state-dropdown#1]
Just want to say my praise for making this public, looks like it would be perfect for something I am currently working on where we allow customers to set up custom localizations within our application.

However I have noticed some of the values such as the Arabic language when selected do not persist in the select box, the value is returned but the value is not marked as selected in the input.

After Arabic selected.
![image](https://github.com/replaysMike/react-country-state-dropdown/assets/14875084/b46c99cd-57fa-444e-aeba-4dc5a7230e05)

After another value selected.
![image](https://github.com/replaysMike/react-country-state-dropdown/assets/14875084/44c1b7b5-db50-4d7f-8a1c-8ccb96eebee6)

I know this project may not have been specifically created to be reused but would be great if it could be :)

UPDATE:

It turns out the issue only happens while using the searchable property and first searching for a value!

**Comment by replaysMike** [comment]
working on an update that was pushed for a later date, I'm going to clean this up and provide an option for lazy loading the data.

**Comment by replaysMike** [comment]
This is now updated as of v1.1.0. I fixed a few bugs, and added support for lazy loading of data files (default, CDN hosted) as well as self-hosting.
